#!/usr/bin/env python3
"""
Rewrite player-facing placeholder copy inside `world/areas/*.yaml`.

Targets (generated by stub/budget helpers):
- "Filler room for ..." / "Seed room for ..."
- "Anchor room for ..." / "Key room stub: ..."
- "Portal stub to ..."

This is intentionally shallow: it does not change topology, exits, ids, or tags.
It only replaces `name` and `desc` so the game is playable while we iterate.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
AREAS_DIR = REPO_ROOT / "world" / "areas"


class Dumper(yaml.SafeDumper):
    pass


def _str_presenter(dumper: yaml.SafeDumper, data: str) -> yaml.nodes.ScalarNode:
    # Keep room prose readable (avoid single-quoted strings with embedded newlines).
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


Dumper.add_representer(str, _str_presenter)


RE_FILLER = re.compile(r"^Filler room for (CL_[A-Z0-9_]+)\. TODO: replace with themed content\.$")
RE_SEED = re.compile(r"^Seed room for (CL_[A-Z0-9_]+)\. TODO: replace with themed content\.$")
RE_ANCHOR = re.compile(r"^Anchor room for ([^.]+)\. TODO: flesh out room graph\.$")
RE_KEY_STUB = re.compile(r"^Key room stub: (R_[A-Z0-9_]+)\. TODO: write original prose\.$")
RE_PORTAL_STUB = re.compile(r"^Portal stub to ([^.]+)\.$")


def err(msg: str) -> None:
    sys.stderr.write(msg.rstrip() + "\n")


def _stable_pick(key: str, options: list[str]) -> str:
    if not options:
        return ""
    h = hashlib.sha1(key.encode("utf-8")).digest()
    idx = int.from_bytes(h[:4], "big") % len(options)
    return options[idx]


def _split_cluster(cluster_id: str) -> tuple[str, str]:
    core = cluster_id[3:] if cluster_id.startswith("CL_") else cluster_id
    if "_" not in core:
        return core, ""
    prefix, rest = core.split("_", 1)
    return prefix, rest


def _friendly_from_room_id(room_id: str) -> str:
    # R_FOO_BAR_01 -> "Bar" / "Foo Bar" (drops the zone token)
    if not room_id.startswith("R_"):
        return room_id.replace("_", " ").title()
    parts = room_id.split("_")
    if len(parts) < 3:
        return room_id
    # Drop "R" + zone token.
    core = parts[2:]
    # Drop numeric suffix if present.
    if core and core[-1].isdigit():
        core = core[:-1]
    label = " ".join(core).replace("  ", " ").strip().title()
    # Insert spaces before digits in tokens like RIFT1.
    label = re.sub(r"([A-Za-z])([0-9])", r"\1 \2", label)
    return label or room_id


def _theme(prefix: str, local: str) -> dict[str, list[str]]:
    """
    Return a dict with:
    - names: list[str]
    - descs: list[str]

    Keep these short. Variety comes from stable hashing on room id.
    """

    p = prefix.upper()
    l = local.upper()

    def pack(names: list[str], descs: list[str]) -> dict[str, list[str]]:
        return {"names": names, "descs": descs}

    # Starter region.
    if p == "MEADOW":
        if "TRAIL" in l:
            return pack(
                ["Trail Bend", "Marker Post", "Grass Path", "Fence Gap", "Sunlit Track", "Cairn"],
                [
                    "Tall grass leans into a packed-dirt trail.\nPainted markers make the way back to town unmissable.",
                    "A narrow path with clear sightlines.\nThe signage here is loud on purpose: you can always retreat.",
                ],
            )
        if "POND" in l:
            return pack(
                ["Reedbank", "Mud Shelf", "Shallow Crossing", "Duckweed Pool", "Drain Runoff"],
                [
                    "Shallow water and reeds mute your footsteps.\nFooting feels worse here; keep your pulls small and readable.",
                    "A slick edge of pondwater reflects the sky.\nIf you get turned around, follow the painted markers back to the trail.",
                ],
            )
        if "PEST" in l or "FIELD" in l:
            return pack(
                ["Field Edge", "Churned Furrow", "Flattened Grass", "Broken Scareline", "Pest Run"],
                [
                    "The grass is churned and noisy with small movement.\nPacks spread out: pace your pulls so you can reset cleanly.",
                    "A stretch of open field with little cover.\nOverpulling is the only real danger here.",
                ],
            )
        if "GRATE" in l or "SEWER" in l:
            return pack(
                ["Overflow Ditch", "Drain Lip", "Maintenance Culvert", "Rusty Grate"],
                [
                    "A maintenance cut in the earth breathes warm air.\nWarning paint points toward the grate and back toward safety.",
                    "An old service grate rattles in its frame.\nThe smell of wet concrete drifts up from below.",
                ],
            )
        return pack(["Meadow Path"], ["Open ground and patient signage.\nThe starter region stays readable by design."])

    if p == "ORCHARD":
        if "GROVE" in l:
            return pack(
                ["Scrap Grove", "Rustleaf Stand", "Metal Rib Row", "Root Hollow", "Tin-Barked Trees"],
                [
                    "Roots knot around old metal ribs half-buried in leaf litter.\nScrap glints in the shade like it wants to be found.",
                    "A quiet grove where metal and wood have grown together.\nEverything here suggests salvage, not safety.",
                ],
            )
        if "ROOT" in l:
            return pack(
                ["Rootworks Squeeze", "Tangle Corridor", "Buried Rib", "Hollowed Trunk", "Tight Turn"],
                [
                    "The path tightens into roots and cover pockets.\nCorners are tools here: break line-of-sight and regroup.",
                    "A cramped run under twisted roots.\nIf ranged drones show up, use the turns to cut their angles.",
                ],
            )
        if "DRONE" in l or "NEST" in l:
            return pack(
                ["Drone Perch", "Buzzing Canopy", "Lantern Branches", "High Nest", "Sightline Break"],
                [
                    "Drones hang in the branches like cold lanterns.\nStay near cover and focus fire when you commit.",
                    "A canopy thick with wires, leaves, and faint motor whine.\nRanged packs punish standing in the open.",
                ],
            )
        if "PIPE" in l:
            return pack(
                ["Pipeway Run", "Coolant Drip", "Bowed Pipe", "Echoing Conduit"],
                [
                    "A service pipeway hums under the roots.\nCool air spills from cracks where the orchard meets the underworks.",
                    "Metal ribs turn into a narrow conduit.\nThe slope down feels like an invitation and a warning.",
                ],
            )
        return pack(["Orchard Trail"], ["Roots and rusted metal shape the paths.\nYou can smell oil under the leaves."])

    if p == "SEWERS":
        if "ENTRY" in l:
            return pack(
                ["Wet Landing", "Service Tunnel", "Painted Arrow", "Low Channel", "Warm Runoff"],
                [
                    "Wet concrete and warm air swallow surface sounds.\nPainted arrows point toward the junction.",
                    "A narrow maintenance run with bolted signage.\nThe route back up is marked for panicked retreats.",
                ],
            )
        if "JUNCTION" in l:
            return pack(
                ["Signpost Chamber", "Chalked Hub", "Regroup Pocket", "Pipe Junction"],
                [
                    "A wide chamber where routes branch cleanly.\nChalk marks track progress like someone expects you to backtrack.",
                    "A stable junction with loud signage.\nThis is a natural regroup point: pause here, then pick a spoke.",
                ],
            )
        if "VALVE" in l:
            return pack(
                ["Hot Pipe Run", "Valve Approach", "Rattling Duct", "Maintenance Walk"],
                [
                    "Pipes tick and creak with pressure.\nEach spoke feels short on purpose: go in, do the job, return to the hub.",
                    "A tight corridor with runoff underfoot.\nRushing here turns small mistakes into wipes.",
                ],
            )
        if "SLUDGE" in l:
            return pack(
                ["Sludge Channel", "Grease Film", "Stagnant Pool", "Grate Crawl", "Low Sump"],
                [
                    "A slow loop of sludge and slippery stone.\nIf something feels unfair, pull back to a safer pocket and reset.",
                    "Warm, dirty water clings to everything.\nThe air tastes metallic, like a battery leaking somewhere nearby.",
                ],
            )
        if "GREASE" in l or "KING" in l:
            return pack(
                ["Oil-Sheen Hall", "Slick Ramp", "Heat Haze", "Greaseway"],
                [
                    "The walls shine with a thin film that catches your light.\nEvery step here wants to become a hazard.",
                    "The air grows warmer and heavier.\nThis route feels like it leads to something that hits back.",
                ],
            )
        return pack(["Service Passage"], ["A maintenance passage of wet concrete and echo.\nSignage is the only comfort."])

    # Mid / late.
    if p == "QUARRY":
        if "FOOTHILL" in l:
            return pack(
                ["Dusty Track", "Spoil Heap", "Rope Line", "Tool Cache"],
                [
                    "Dust hangs in the air and grit crunches underfoot.\nThe world smells like stone and hot metal.",
                    "A rough track along the quarry edge.\nYou can hear machinery somewhere, even when you can't see it.",
                ],
            )
        if "WORK" in l:
            return pack(
                ["Foreman Yard", "Ore Cart Lane", "Crane Shadow", "Breaker Pad"],
                [
                    "Stenciled warnings and battered equipment mark the works.\nThis place teaches: stand where the heavy things are not.",
                    "A busy stretch of industrial ground.\nEven abandoned, it feels like a job site that expects rules.",
                ],
            )
        if "PIT" in l:
            return pack(
                ["Open Pit", "Rock Face", "Loose Scree", "Blasted Shelf", "Shattered Ledge"],
                [
                    "The pit drops away into shadow.\nEvery fight here feels heavier because there is nowhere easy to run.",
                    "Broken stone and sharp angles.\nFooting is fine, but sightlines are not.",
                ],
            )
        if "ILLEGAL" in l or "DIG" in l:
            return pack(
                ["Tarped Cut", "Hidden Shaft", "Quiet Ramp", "Smuggler Crawl"],
                [
                    "Tarps and makeshift braces hide a dig that shouldn't exist.\nSomeone wanted this work unseen.",
                    "A hush hangs over the rock.\nEven the dust here feels like evidence.",
                ],
            )
        return pack(["Quarry Track"], ["A rough industrial stretch of stone and dust.\nYou can taste grit when you breathe."])

    if p == "CHECKPOINT":
        return pack(
            ["Road Barrier", "Toll Post", "Sandbag Line", "Weathered Sign", "Guard Spur"],
            [
                "A checkpoint of patched concrete and tired signage.\nThe road beyond looks longer than it used to.",
                "A travel choke point with clear lines and nowhere to hide.\nIf you pick a fight here, you own it.",
            ],
        )

    if p == "HILLFORT":
        if "BUNKER" in l or "COMMAND" in l:
            return pack(
                ["Command Bunker", "Briefing Room", "Safe Niche", "Ward Console"],
                [
                    "A sheltered pocket with old maps and newer chalk.\nIt feels like a place you can breathe without being hunted.",
                    "Concrete, dust, and the faint smell of ozone.\nSomeone rebuilt a little safety inside the ruin.",
                ],
            )
        if "BANNER" in l or "HALL" in l:
            return pack(
                ["Banner Hall", "Cracked Gallery", "Old Parade Way", "Trophy Arch"],
                [
                    "A wide hall where every sound carries.\nYou can almost feel the shape of a boss arena.",
                    "Stone flags and torn banners.\nThis room wants an ending.",
                ],
            )
        return pack(
            ["Broken Rampart", "Ward Pylon Path", "Courtyard Rubble", "Collapsed Walk"],
            [
                "Crumbling fort stone and wind through empty gaps.\nPatrol routes feel intentional, like a lesson in timing.",
                "Rubble and old pylons break up sightlines.\nPick your route instead of taking every fight.",
            ],
        )

    if p == "RAIL":
        if "TERMINAL" in l:
            return pack(
                ["Terminal Shed", "Ticket Booth", "Loading Dock", "Service Office"],
                [
                    "A terminal that still thinks it has a schedule.\nThe metal underfoot is cold even when the air is not.",
                    "Faded signage and a stubborn hum from somewhere in the walls.\nThis place is a hub for trouble.",
                ],
            )
        if "YARD" in l:
            return pack(
                ["Switch Stand", "Yard Spur", "Signal Post", "Ballast Run"],
                [
                    "Steel lines split and rejoin across crushed rock.\nGeometry matters here: use cover and angles.",
                    "A rail yard that feels half-alive.\nSomething moves when you aren't looking.",
                ],
            )
        return pack(
            ["Rail Line", "Track Cut", "Service Spur", "Signal Walk"],
            [
                "The rail line stretches forward like a promise.\nTravel is possible, but never free.",
                "A long straight run with harsh sightlines.\nIf an event hits, you will see it coming.",
            ],
        )

    if p == "RUSTWOOD":
        if "CAMP" in l or "RANGER" in l:
            return pack(
                ["Ranger Camp", "Map Board", "Firepit Ring", "Supply Cache"],
                [
                    "A small camp with maps nailed to a board.\nSomeone here expects you to get lost and come back anyway.",
                    "A quiet rest pocket under the trees.\nThe forest beyond feels larger than the paths suggest.",
                ],
            )
        if "PYLON" in l:
            return pack(
                ["Pylon Clearing", "Rust Tower Shadow", "Broken Fence", "Wire Grove"],
                [
                    "A clearing dominated by a rusted pylon.\nHumming wires suggest the old grid never fully died.",
                    "Trees grow around metal like it is natural.\nSightlines are strange here; listen before you pull.",
                ],
            )
        return pack(
            ["Forest Trail", "Mossy Track", "Thorned Turn", "Foggy Hollow"],
            [
                "A forest trail where rusted debris hides in the needles.\nPredators prefer ambushes, not fair fights.",
                "Branches swallow the sky.\nIf you hear something you can't see, that's the point.",
            ],
        )

    if p == "LIB":
        if "STACK" in l:
            return pack(
                ["Stack Row", "Archive Aisle", "Shelf Canyon", "Index Nook"],
                [
                    "Tall shelves make a maze of quiet corridors.\nWater damage turns paper into a smell you can taste.",
                    "A cramped aisle between leaning stacks.\nSound travels strangely, like the room is listening.",
                ],
            )
        if "FLOOD" in l:
            return pack(
                ["Flooded Wing", "Waterlogged Hall", "Slick Step", "Drowned Alcove"],
                [
                    "Cold water pools around broken tiles.\nEvery step risks noise and slow movement.",
                    "A wing claimed by damp and mold.\nVisibility is worse, and so are your choices.",
                ],
            )
        if "DECODER" in l:
            return pack(
                ["Decoder Chamber", "Cipher Door", "Plate Socket", "Control Lectern"],
                [
                    "An old chamber built around a stubborn machine.\nIt feels like the kind of puzzle that only opens for effort.",
                    "Metal plates and engraved sockets wait for missing pieces.\nThe air tastes like ozone and wet stone.",
                ],
            )
        return pack(
            ["Library Hall", "Antechamber", "Broken Reading Room", "Dusty Vestibule"],
            [
                "A flooded archive where light goes to die.\nKnowledge is a key here, not a flavor.",
                "Stone and shelving frame a cold, damp hush.\nEven empty rooms feel watched.",
            ],
        )

    if p == "FACTORY":
        if "CONVEYOR" in l:
            return pack(
                ["Conveyor Walk", "Belt Overpass", "Jam Point", "Line Access"],
                [
                    "Conveyor belts and guardrails shape every fight.\nIf you ignore the moving parts, you deserve what happens.",
                    "A loud industrial lane with constant motion.\nLearn the timing or get punished for standing still.",
                ],
            )
        if "FOUNDRY" in l:
            return pack(
                ["Foundry Catwalk", "Heat Channel", "Slag Pit Edge", "Weld Bay"],
                [
                    "Heat wavers off metal you shouldn't touch.\nThe room teaches interrupts the hard way.",
                    "A foundry lane of vents and sparks.\nYou can smell hot oil under the air filters.",
                ],
            )
        if "SWITCH" in l:
            return pack(
                ["Switchroom Hall", "Control Closet", "Breaker Panel", "Relay Aisle"],
                [
                    "Control panels blink with stubborn intent.\nThis is where routes and systems get decided.",
                    "A narrow room of switches and warnings.\nEverything is labeled, but not helpfully.",
                ],
            )
        return pack(
            ["Service Street", "Factory Gate", "Loading Lane", "Pipe Alley"],
            [
                "Concrete corridors and industrial noise.\nLine-of-sight is a weapon here.",
                "A tight urban-industrial stretch.\nCorners hide both cover and danger.",
            ],
        )

    if p == "RES":
        if "PUMP" in l:
            return pack(
                ["Pump Station", "Valve Deck", "Intake Walk", "Control Gantry"],
                [
                    "A station of pipes, pressure gauges, and constant vibration.\nWater and power share the same nerves here.",
                    "A damp deck with warning lights that never fully go dark.\nIf the pumps fail, the world notices.",
                ],
            )
        if "SHORE" in l:
            return pack(
                ["Reservoir Shore", "Wet Dock", "Reedline", "Concrete Steps"],
                [
                    "Wide water and exposed sightlines.\nRanged threats feel bigger when there is nowhere to duck.",
                    "A shoreline of concrete and weeds.\nThe surface looks calm; the infrastructure does not.",
                ],
            )
        if "TUNNEL" in l:
            return pack(
                ["Service Tunnel", "Wet Passage", "Pressure Gate", "Echo Run"],
                [
                    "A tunnel that carries water, power, and bad ideas.\nAmbushes are easier here than honesty.",
                    "A narrow run of dripping stone and pipe.\nEvery sound comes back wrong.",
                ],
            )
        if "CONTROL" in l or "NODE" in l:
            return pack(
                ["Control Node", "Regulator Panel", "Sensor Pod", "Valve Cluster"],
                [
                    "A control node buried in pipework.\nThe interface looks simple and lies about it.",
                    "A pocket of machinery that wants a deliberate hand.\nIf you rush, you will flip the wrong thing.",
                ],
            )
        if "FLOW" in l or "REGULATOR" in l:
            return pack(
                ["Flow Regulator Way", "Pressure Chamber", "Gate Deck", "Surge Hall"],
                [
                    "The pipes here feel too large to trust.\nThis route leads toward a fight with phases.",
                    "A chamber built to tame force.\nIt has the vibe of a boss room you haven't earned yet.",
                ],
            )
        return pack(["Reservoir Walk"], ["Damp concrete and heavy pipework.\nEverything here is about control."])

    if p == "UNDERRAIL":
        if "PLATFORM" in l:
            return pack(
                ["Platform Edge", "Arrival Deck", "Signal Booth", "Stairwell"],
                [
                    "A platform carved into a buried transit spine.\nOld signs still insist trains exist.",
                    "Cold air and distant vibrations.\nThis is a hub for deep travel, not a safe home.",
                ],
            )
        if "SWITCH" in l or "YARD" in l:
            return pack(
                ["Switchyard", "Track Split", "Signal Cross", "Maintenance Bay"],
                [
                    "Rails and signals crisscross in the dark.\nTiming and route choice matter more than raw damage.",
                    "A long loop of trackwork and blinking lights.\nPatrols feel like clockwork.",
                ],
            )
        return pack(
            ["Signal Tunnel", "Cable Run", "Low Passage", "Marker Alcove"],
            [
                "A tunnel lined with cables and old signal boxes.\nThe dark here feels planned, not accidental.",
                "A narrow run with harsh acoustics.\nIf you hear steps, assume they're not yours.",
            ],
        )

    if p == "SKY":
        if "ANCHOR" in l:
            return pack(
                ["Anchorhouse", "Bolt Room", "Chain Deck", "Winch Bay"],
                [
                    "A steel anchorhouse that hums under tension.\nIf this fails, the spans stop being spans.",
                    "Bolts, chains, and wind that never fully rests.\nThis is a hub for dangerous travel.",
                ],
            )
        if "SPAN" in l:
            return pack(
                ["Span Walk", "Wind Cut", "Guardrail Gap", "Long Sightline"],
                [
                    "A long open span with nothing to hide behind.\nWind punishes indecision.",
                    "Steel underfoot and open air on both sides.\nRanged threats feel personal here.",
                ],
            )
        return pack(
            ["Skybridge Path", "Anchor Run", "Cable Walk", "High Deck"],
            [
                "High air, long sightlines, and constant wind.\nMovement matters as much as damage.",
                "A narrow path above a long drop.\nIf you panic, go back the way you came.",
            ],
        )

    if p == "WASTES":
        if "OUTPOST" in l:
            return pack(
                ["Outpost Yard", "Shelter Wall", "Water Cache", "Windbreak"],
                [
                    "A low outpost built to survive storms, not enemies.\nShelter feels like progress here.",
                    "Glass-scarred boards and patched fabric walls.\nThe outpost is a checkpoint you can believe in.",
                ],
            )
        if "DUNE" in l:
            return pack(
                ["Dune Run", "Sand Cut", "Leeward Hollow", "Heat Ripple"],
                [
                    "Wind-carved dunes shift underfoot.\nLandmarks are rare; pick a line and commit.",
                    "Heat haze makes distance feel fake.\nIf you lose your bearing, head for shelter.",
                ],
            )
        if "GLASS" in l:
            return pack(
                ["Glassed Flat", "Shardfield", "Crackled Ground", "Mirror Patch"],
                [
                    "Glassed ground crunches like thin ice.\nEvery step wants to cut, chip, or give you away.",
                    "A field of fused sand and sharp edges.\nStorms turn this place into a weapon.",
                ],
            )
        if "EYE" in l or "STORM" in l:
            return pack(
                ["Storm Eye", "Static Pocket", "Calm Ring", "Pressure Drop"],
                [
                    "The storm changes pitch, then holds its breath.\nThis calm feels like a trap and a promise.",
                    "A strange pocket of stillness inside the wind.\nIf an event triggers, it will be here.",
                ],
            )
        return pack(["Wastes Track"], ["Heat haze and sharp ground.\nShelter is the only reliable landmark."])

    if p == "GARDENS":
        if "GREENHOUSE" in l:
            return pack(
                ["Greenhouse Gate", "Decon Pad", "Glass Door", "Humidity Lock"],
                [
                    "A greenhouse threshold with decon spray and clean lines.\nInside, the plants feel engineered, not grown.",
                    "Glass panels and humming fans.\nThis is a hub that insists on safety protocols.",
                ],
            )
        if "BLOOM" in l or "GROVE" in l:
            return pack(
                ["Bloom Grove", "Vine Arch", "Spore Drift", "Caretaker Lane"],
                [
                    "Engineered plants crowd the path with deliberate beauty.\nSomething here is harvesting you back.",
                    "A grove where flowers look too perfect.\nIf you linger, something notices.",
                ],
            )
        if "ENGINE" in l:
            return pack(
                ["Root Engine Way", "Feedline Trench", "Pressure Root", "Thrum Chamber"],
                [
                    "Roots wrap around ancient machinery that still pulses.\nThis route points toward a multi-stage fight.",
                    "A low thrum vibrates through soil and metal.\nThe garden is not the thing in charge here.",
                ],
            )
        return pack(
            ["Garden Wilds", "Overgrown Path", "Sunken Bed", "Rusty Trellis"],
            [
                "Overgrowth hides old machinery in plain sight.\nThe wilderness is curated, not natural.",
                "Plants reclaim metal with quiet stubbornness.\nYou can smell pollen and hot oil together.",
            ],
        )

    if p == "CORE":
        if "GATE" in l or "RING" in l:
            return pack(
                ["Gate Ring", "Entry Halo", "Sentinel Walk", "Lockstep Plaza"],
                [
                    "A ring of machine stone with precise seams.\nIt feels like the world is checking your posture.",
                    "An entry ring where every surface looks intentional.\nIf there is a test, it starts here.",
                ],
            )
        if "AUDITOR" in l or "ARENA" in l:
            return pack(
                ["Auditor Hall", "Judgment Floor", "Resonance Bowl", "Final Approach"],
                [
                    "The space opens into something built for evaluation.\nYour mistakes will be obvious here.",
                    "A wide chamber with too few places to hide.\nIt has boss-room honesty.",
                ],
            )
        return pack(
            ["Core Passage", "Innerworks Run", "Machine Walk", "Servo Gallery"],
            [
                "Ancient machinery hums behind the walls.\nEvery room feels like part of a larger organism.",
                "Clean geometry and cold air.\nThis place rewards coordination, not bravery.",
            ],
        )

    if p == "SEAM":
        if "EDGE" in l or "STATION" in l:
            return pack(
                ["Edge Station", "Staging Bay", "Signal Room", "Quiet Threshold"],
                [
                    "A station built at the boundary where rules start to slip.\nWarning placards feel more like prayers.",
                    "Cold light and faint static.\nThis is a hub where you check your gear twice.",
                ],
            )
        if "RIFT" in l:
            return pack(
                ["Rift Scar", "Frayed Corridor", "Static Cut", "Impossible Angle"],
                [
                    "Reality looks scraped, like the world hit a rough edge.\nThe air tastes like ozone and old dust.",
                    "A rift-worn passage where shadows behave badly.\nIf something feels like a bug, it might be the feature.",
                ],
            )
        if "NEXUS" in l or "STABILIZER" in l:
            return pack(
                ["Stabilizer Nexus", "Anchor Chamber", "Control Lattice", "Restraint Ring"],
                [
                    "A chamber built to hold the boundary together.\nThe hum here feels like pressure under glass.",
                    "Metal latticework and calm, threatening light.\nThis is where the world gets stitched.",
                ],
            )
        if "MAZE" in l:
            return pack(
                ["Seam Maze", "Mirror Turn", "False Door", "Looping Hall"],
                [
                    "A corridor that refuses to stay the same.\nKeep your party tight and your route explicit.",
                    "Geometry twists like it is thinking.\nIf you get lost, that is the mechanic.",
                ],
            )
        return pack(["Seam Passage"], ["Static and cold light.\nThe boundary makes everything feel slightly wrong."])

    # Fallback: at least remove TODO/placeholder vibes.
    label = local.replace("_", " ").title() if local else prefix.title()
    return pack(
        [label],
        [
            f"{label} stretches onward.\nThe space feels maintained by something that does not sleep.",
            f"You move through {label.lower()}.\nOld signage suggests this place has rules, even if you don't know them yet.",
        ],
    )


def _apply_room_copy(zone_name: str, room: dict, kind: str, portal_target: str | None = None) -> int:
    rid = room.get("id")
    cid = room.get("cluster")
    if not isinstance(rid, str) or not isinstance(cid, str):
        return 0

    prefix, local = _split_cluster(cid)
    theme = _theme(prefix, local)

    # Name.
    name = room.get("name")
    if kind in {"filler", "seed", "key"}:
        room["name"] = _stable_pick(rid, theme["names"])
    elif kind == "anchor":
        # Keep existing "Anchor" name if present, but make it readable if it's just the id.
        if not isinstance(name, str) or name.strip() == "" or name == rid:
            room["name"] = _stable_pick(rid, theme["names"])
    elif kind == "portal":
        # Portal rooms are boundary markers; keep their existing names unless they're empty.
        if not isinstance(name, str) or name.strip() == "":
            room["name"] = "Transfer"

    # Description.
    if kind == "portal" and portal_target:
        room["desc"] = f"A marked boundary with a clear way out.\nBeyond lies {portal_target}."
    else:
        room["desc"] = _stable_pick(rid, theme["descs"])

    return 1


def themify_zone(zone_id: str, areas_dir: Path, dry_run: bool) -> int:
    path = areas_dir / f"{zone_id}.yaml"
    if not path.exists():
        err(f"error: missing area file: {path.relative_to(REPO_ROOT)}")
        return 2

    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        err(f"error: invalid yaml (expected mapping): {path.relative_to(REPO_ROOT)}")
        return 2

    zone_name = doc.get("zone_name") if isinstance(doc.get("zone_name"), str) else zone_id
    rooms = doc.get("rooms")
    if not isinstance(rooms, list) or not rooms:
        err(f"error: missing rooms list: {path.relative_to(REPO_ROOT)}")
        return 2

    changed = 0
    for room in rooms:
        if not isinstance(room, dict):
            continue
        desc = room.get("desc")
        if not isinstance(desc, str):
            continue

        m = RE_FILLER.match(desc)
        if m:
            changed += _apply_room_copy(zone_name, room, kind="filler")
            continue

        m = RE_SEED.match(desc)
        if m:
            changed += _apply_room_copy(zone_name, room, kind="seed")
            continue

        m = RE_ANCHOR.match(desc)
        if m:
            changed += _apply_room_copy(zone_name, room, kind="anchor")
            continue

        m = RE_KEY_STUB.match(desc)
        if m:
            # Also fix unreadable names like "R_FOO_BAR_01".
            if isinstance(room.get("name"), str) and room["name"] == m.group(1):
                room["name"] = _friendly_from_room_id(m.group(1))
            changed += _apply_room_copy(zone_name, room, kind="key")
            continue

        m = RE_PORTAL_STUB.match(desc)
        if m:
            changed += _apply_room_copy(zone_name, room, kind="portal", portal_target=m.group(1))
            continue

    if changed == 0:
        sys.stdout.write(f"{zone_id}: no placeholders found\n")
        return 0

    if dry_run:
        sys.stdout.write(f"{zone_id}: would rewrite {changed} room(s)\n")
        return 0

    path.write_text(yaml.dump(doc, Dumper=Dumper, sort_keys=False, width=120), encoding="utf-8")
    sys.stdout.write(f"{zone_id}: rewrote {changed} room(s)\n")
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--areas-dir", default=str(AREAS_DIR))
    ap.add_argument("--zone-id", action="append", default=[], help="Themify only this zone_id (repeatable)")
    ap.add_argument("--all", action="store_true", help="Themify every area file found in world/areas/")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    areas_dir = Path(args.areas_dir)
    if args.all:
        zone_ids = sorted([p.stem for p in areas_dir.glob("*.yaml")])
    else:
        zone_ids = list(args.zone_id)

    if not zone_ids:
        err("error: pass --all or at least one --zone-id")
        return 2

    rc = 0
    for zid in zone_ids:
        rc = max(rc, themify_zone(zid, areas_dir, dry_run=bool(args.dry_run)))
        if rc != 0:
            return rc
    return rc


if __name__ == "__main__":
    raise SystemExit(main(__import__("sys").argv[1:]))

