#!/usr/bin/env bash
set -euo pipefail

# Create a per-agent local env file with an isolated port block.
#
# Usage:
#   scripts/mk_agent_env.sh <name> <base_port> <out_path>
#
# Port layout (base must be >=1024):
#   broker/session tcp: base+0
#   shard:             base+1
#   oauth web:         base+2
#   static web:        base+3
#   ws gateway:        base+4
#   admin json:        base+11
#
# Recommendation: use base ports spaced by 100 between agents (ex: 4940, 5040, 5140, ...).

name="${1:-}"
base="${2:-}"
out="${3:-}"

if [[ -z "${name}" || -z "${base}" || -z "${out}" ]]; then
  echo "usage: $0 <name> <base_port> <out_path>" >&2
  exit 2
fi

if ! [[ "${base}" =~ ^[0-9]+$ ]]; then
  echo "base_port must be an integer" >&2
  exit 2
fi

if (( base < 1024 )); then
  echo "base_port must be >= 1024 (avoid privileged ports)" >&2
  exit 2
fi

broker_port=$((base + 0))
shard_port=$((base + 1))
oauth_port=$((base + 2))
static_port=$((base + 3))
ws_port=$((base + 4))
admin_port=$((base + 11))

mkdir -p "$(dirname "${out}")"

cat >"${out}" <<EOF
# autogenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# agent: ${name}
# base_port: ${base}
ENV_NAME=agent-${name}

# Isolate cargo artifacts between agents/worktrees.
CARGO_TARGET_DIR=/tmp/slopmud_target_${name}

# --- slopmud (session broker) ---
SLOPMUD_BIND=127.0.0.1:${broker_port}
SESSION_TCP_ADDR=127.0.0.1:${broker_port}
SHARD_ADDR=127.0.0.1:${shard_port}
SLOPMUD_ADMIN_BIND=127.0.0.1:${admin_port}
SLOPMUD_ACCOUNTS_PATH=/tmp/slopmud_accounts_${name}.json
SLOPMUD_GOOGLE_AUTH_BASE_URL=http://127.0.0.1:${oauth_port}

# Keep SBC sockets per-agent so multiple brokers can run concurrently.
SBC_ADMIN_SOCK=/tmp/slopmud_sbc_admin_${name}.sock
SBC_EVENTS_SOCK=/tmp/slopmud_sbc_events_${name}.sock

# --- shard ---
SHARD_BIND=127.0.0.1:${shard_port}

# --- web ---
STATIC_WEB_BIND=127.0.0.1:${static_port}
OAUTH_WEB_BIND=127.0.0.1:${oauth_port}
WS_BIND=127.0.0.1:${ws_port}

# --- tuning ---
WORLD_TICK_MS=200
BARTENDER_EMOTE_MS=1000
RUST_BACKTRACE=1

# --- secrets ---
# Secrets must be stored under \$SECRET_STORE and referenced by name (never committed).
EOF

echo "wrote ${out}"
