[package]
name = "slopmud_walbackup"
version = "0.1.0"
edition = "2024"
license = "MIT OR 0BSD"

[dependencies]
anyhow = "1.0.96"
aws-config = { version = "1.5.13", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.74.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
